apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            # BUILD: esta línea es la que cambia el script en cada corrida
            - -text=build 244674
          ports:
            - containerPort: 5678
